Feature responsive desktop version
lewisjn-arch/Mobile-Portfolio-setup pull request #4
Opened 2023-06-09 07:45 UTC by lewisjn-arch

This PR request contains the following changes:

- [ ] I have grouped containers in html for desktop optimization.
- [ ] I have added media queries for the desktop version.
- [ ] I have made the page responsive upto a maximum width of 1440px.

NOTE: I am still configuring the container widths to respond to screens wider than 1440px.

2023-06-09 08:45 UTC, AlphaNtihinduka requested changes
## Hi @lewisjn-arch 🙋‍♂️
Good job working on your desktop version. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement a few on the project but you are almost there!!! 🚶 : 

TO HIGHLIGHT:
- Design matches the Figma design ✔️
- Desktop size starts at 768px ✔️
- Well-structured files ✔️

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)


# Required Changes :recycle: 
- _Kindly consider the inline comments_ ☺️ 
- [ ] Please try as much as possible to ensure that your application does not have a horizontal scroll. The experience of scrolling horizontally can make the screen judder and create a headache-inducing feeling 😞 . Please fix this to have a professional portfolio ☺️ 
https://github.com/lewisjn-arch/Mobile-Portfolio-setup/assets/99394374/de78b7cc-c4d9-42e3-ae34-42b201d5962d



## Optional suggestions
N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-06-09 08:45 UTC, AlphaNtihinduka commented on index.html
> +        <div class="desktop_illustration_triangle"></div>
- [ ] I have noticed that you are using different image backgrounds for an image that should be one. I suggest that you use only on background in the banner. This is to make sure that your portfolio is professional and easy to maintain.
- [ ] In addition, the background image should not have its `div` instead it should be used in the section or under HTML tag. For example for this particular case, the background image should be attached to `headline` ☺️.
Hint: You can consider exporting the illustration header which will download the whole image.
![image](https://github.com/lewisjn-arch/Mobile-Portfolio-setup/assets/99394374/1eba4f0a-b2c8-4ae9-8535-fa0607e0e3e1)

2023-06-09 08:45 UTC, AlphaNtihinduka commented on index.html
>          <div class="about_me_illustration"></div>
- As mentioned earlier about the background, the background image should not have its `div` instead it should be used in the section or under the HTML tag. For example for this particular case, the background image should be attached to the `about-me-container` or `about-me` ☺️.

2023-06-09 09:50 UTC, lewisjn-arch commented on index.html
>          <div class="about_me_illustration"></div>
Thank you so much I thought I was so far from approval because it the desktop version isn't responsive beyond 1440px width

2023-06-09 17:29 UTC, lewisjn-arch commented
This second review request has the following:

- [ ] I attached the background images to page containers using css.
- [ ] I changed some dimensions to their relative equivalents.


NOTE: I am suddenly getting a webhint error that I have failed to fix, I am getting an error that I do not understand in the details despite deleting and reinstalling linters files again.

2023-06-09 17:35 UTC, shahadat3669 requested changes
Hi @lewisjn-arch , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project, that is invalid because of linter errors.
- To ensure that your code adheres to the project's linting standards, it is important to have a green linter result. This means that the last commit in your pull request should have a green check mark (:white\_check\_mark:) or a summary indicating that all the required checks have passed. This helps in maintaining a clean and consistent codebase.

| Your | Professional |
| --- | --- |
| ![image](https://github.com/lewisjn-arch/Mobile-Portfolio-setup/assets/55840999/9e191104-6205-46dd-9522-c1212a09e356) | ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/c0b6376f-da9b-4e03-8dfc-c334b22977b2) |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 07:51 UTC, lewisjn-arch commented
This second re-review request has the following:

 - [ ] I attached the background images to page containers using css.
 - [ ] I changed some dimensions to their relative equivalents.


NOTE: I am suddenly getting a webhint error that I have failed to fix, I am getting an error that I do not understand in the details despite deleting and reinstalling linters files again.

![Screenshot (18)](https://github.com/lewisjn-arch/Mobile-Portfolio-setup/assets/123990686/799f4afb-6082-43c4-865d-055e582611a9)

2023-06-10 08:21 UTC, emmiiorji approved these changes
Hi @lewisjn-arch, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Requested changes have been implemented

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 08:21 UTC, emmiiorji commented on index.html
> +                <button type="button" class="project_link"><span class="link_text">See project</span></button>
[Optional] A close look at the figma design for the cards shows two displays for the cards. The first card with the "See Project" button shows how each card should look when hovered while the remaining cards without the "See Project" button shows how the cards will look without a hover.

Project card when hovered:
![image](https://github.com/lewisjn-arch/Mobile-Portfolio-setup/assets/20554583/2b825e3f-3764-4885-9d7f-9d8587bc9b74)

Project card without hover:
![image](https://github.com/lewisjn-arch/Mobile-Portfolio-setup/assets/20554583/a2494b72-91b5-490d-bfbd-8b9d96f622d0)

2023-06-10 09:37 UTC, merged